# Generated by Django 5.2.1 on 2025-06-04 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['timestamp'], name='analytics_p_timesta_835321_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['path'], name='analytics_p_path_3382b5_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['user'], name='analytics_p_user_id_23554e_idx'),
        ),
    ]
